version: '3.8'

services:
  db:
    container_name: foodgram-db
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    container_name: foodgram-app
    image: shivazoid/foodgram_backend:latest
    volumes:
      - static_dir:/app/static/
      - media_dir:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    container_name: foodgram-front
    image: shivazoid/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend

  nginx:
    container_name: foodgram-proxy
    image: nginx:1.21.3-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_dir:/etc/nginx/html/static/
      - media_dir:/etc/nginx/html/media/
    depends_on:
      - frontend

volumes:
  static_dir:
  media_dir:
  postgres_data:
