# Generated by Django 4.2 on 2023-05-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredientinrecipe',
            name='\nrecipes_ingredientinrecipe ingredient alredy added\n',
        ),
        migrations.AddConstraint(
            model_name='ingredientinrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredients'), name='\nrecipes_ingredientinrecipe ingredient alredy added\n'),
        ),
    ]
